=== himanshuhsshar/SOAP-and-Restful/Workspace/xsd-xml/NAMESPACES/po.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:sna="http://www.sbi.com/netbanking/accounts" targetNamespace="http://www.sbi.com/netbanking/accounts" elementFormDefault="qualified">
	<xs:element name="account" type="sna:accountType"/>
	<xs:complexType name="accountType">
		<xs:sequence>
			<xs:element name="account-no" type="xs:string"/>
			<xs:element name="account-holder-nm" type="xs:string"/>
			<xs:element name="opened-dt" type="xs:date"/>
			<xs:element name="account-type" type="xs:string"/>
			<xs:element name="registered-mobile-no" type="xs:string"/>
			<xs:element name="registered-email-address" type="xs:string"/>
			<xs:element name="balance" type="xs:float"/>
			<xs:element name="address" type="sna:addressType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="address-line1" type="xs:string"/>
			<xs:element name="address-line2" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="xs:int"/>
			<xs:element name="country" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/Workspace/xsd-xml/NAMESPACES/account.xml
<?xml version="1.0" encoding="UTF-8"?>
<sa:account xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sbi.com/netbanking/accounts file:///D:/work/master/webservices/20223003/NAMESPACES/po.xsd" xmlns:sa="http://www.sbi.com/netbanking/accounts">
	<sa:account-no>ac9833</sa:account-no>
	<sa:account-holder-nm>Fedrick</sa:account-holder-nm>
	<sa:opened-dt>2022-01-12</sa:opened-dt>
	<sa:account-type>savings</sa:account-type>
	<sa:registered-mobile-no>989373789</sa:registered-mobile-no>
	<sa:registered-email-address>fedrick@gmail.com</sa:registered-email-address>
	<sa:balance>3944</sa:balance>
	<sa:address>
		<sa:address-line1>1837, joseph st</sa:address-line1>
		<sa:address-line2>north highway</sa:address-line2>
		<sa:city>columbus</sa:city>
		<sa:state>ohio</sa:state>
		<sa:zip>9377</sa:zip>
		<sa:country>USA</sa:country>
	</sa:address>
</sa:account>
