=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/passport.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2011 sp1 (http://www.altova.com) by End User (free.org) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="passport" type="passportType"/>
	<xs:complexType name="passportType">
		<xs:sequence>
			<xs:element name="passport-no" type="xs:string"/>
			<xs:element name="fullname" type="xs:string"/>
			<xs:element name="dob" type="xs:date"/>
			<xs:element name="gender" type="genderType"/>
			<xs:element name="expiry-date" type="xs:date"/>
			<xs:element name="issued-date" type="xs:date"/>
			<xs:element name="issued-authority" type="xs:string"/>
			<xs:element name="address" type="addressType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="addressType">
		<xs:sequence>
			<xs:element name="address-line1" type="xs:string"/>
			<xs:element name="address-line2" type="xs:string"/>
			<xs:element name="city" type="xs:string"/>
			<xs:element name="state" type="xs:string"/>
			<xs:element name="zip" type="zipType"/>
			<xs:element name="country" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="genderType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="male"/>
			<xs:enumeration value="female"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="zipType">
		<xs:restriction base="xs:int">
			<xs:totalDigits value="5"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/passport.xml
<?xml version="1.0" encoding="UTF-8"?>
<passport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebServices/XSD/passport.xsd">
	<passport-no>P01234</passport-no>
	<fullname>Himanshu Sharma</fullname>
	<dob>1998-01-07</dob>
	<gender>male</gender>
	<expiry-date>2025-01-23</expiry-date>
	<issued-date>2020-01-03</issued-date>
	<issued-authority>Hyderabad Passport Office</issued-authority>
	<address>
		<address-line1>12 Avenue</address-line1>
		<address-line2>Parklane Street</address-line2>
		<city>Hyderabad</city>
		<state>TamilNadu</state>
		<zip>86976</zip>
		<country>India</country>
	</address>
	
</passport>

=== himanshuhsshar/SOAP-and-Restful/XSD/passport.xml
<?xml version="1.0" encoding="UTF-8"?>
<passport xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20223003/XSD/passport.xsd">
	<passport-no>p03893</passport-no>
	<fullname>gerold</fullname>
	<dob>1989-01-12</dob>
	<gender>male</gender>
	<expiry-date>2025-01-23</expiry-date>
	<issued-date>2020-01-22</issued-date>
	<issued-authority>Hyderabad Passport Office</issued-authority>
	<address>
		<address-line1>12 avenue</address-line1>
		<address-line2>parklane street</address-line2>
		<city>hyderabad</city>
		<state>ts</state>
		<zip>89383</zip>
		<country>India</country>
	</address>
</passport>
