=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="policy">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="policy-no" type="xs:string"/>
				<xs:element name="policy-holder-name" type="xs:string"/>
				<xs:element name="policy-type" type="xs:string"/>
				<xs:element name="tenure" type="xs:int"/>
				<xs:element name="premiun-amount" type="xs:string"/>
				<xs:element name="insurred-amount" type="xs:float"/>
				<xs:element name="nominee">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="fullname" type="xs:string"/>
							<xs:element name="dob" type="xs:date"/>
							<xs:element name="gender" type="xs:string"/>
							<xs:element name="relationship" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/XSD/policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<policy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20223003/XSD/policy.xsd">
	<policy-no>p0383</policy-no>
	<policy-holder-name>kevin peterson</policy-holder-name>
	<policy-type>risk coverage</policy-type>
	<tenure>180</tenure>
	<premium-amount>4500</premium-amount>
	<insurred-amount>200000</insurred-amount>
	<nominee>
		<fullname>pam</fullname>
		<dob>1985-01-20</dob>
		<gender>female</gender>
		<relationship>wife</relationship>
	</nominee>
</policy>

=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<policy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebServices/XSD/policy.xsd">
	<policy-no>p0383</policy-no>
	<policy-holder-name>Keven Peterson</policy-holder-name>
	<policy-type>risk coverage</policy-type>
	<tenure>180</tenure>
	<premiun-amount>4500</premiun-amount>
	<insurred-amount>200000</insurred-amount>
	<nominee>
		<fullname>Pam</fullname>
		<dob>1985-01-20</dob>
		<gender>female</gender>
		<relationship>wife</relationship>
	</nominee>
</policy>
