=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/tour-packages.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="tour-package" type="tourPackageType"/>
	<xs:complexType name="tourPackageType">
		<xs:sequence>
			<xs:element name="package-no" type="xs:int"/>
			<xs:element name="package-name" type="xs:string"/>
			<xs:element name="days" type="xs:int"/>
			<xs:element name="nights" type="xs:int"/>
			<xs:element name="package-amount" type="xs:float"/>
			<xs:element name="place" type="placesType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="placesType">
		<xs:choice>
			<xs:element name="domestic-place" type="domesticPlaceType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="international-place" type="internationalPlaceType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="domesticPlaceType">
		<xs:sequence>
			<xs:element name="place-name" type="xs:string"/>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="travel-mode" type="xs:string"/>
			<xs:element name="hours" type="xs:int"/>
			<xs:element name="description" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="internationalPlaceType">
		<xs:complexContent>
			<xs:extension base="domesticPlaceType">
				<xs:sequence>
					<xs:element name="passport-required" type="xs:boolean"/>
					<xs:element name="visa-required" type="xs:boolean"/>
					<xs:element name="age-limit" type="xs:int"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/tour-packages.xml
<?xml version="1.0" encoding="UTF-8"?>
<tour-package xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebServices/XSD/tour-packages.xsd">
	<package-no>983</package-no>
	<package-name>Sparkling Darjeeling</package-name>
	<days>4</days>
	<nights>5</nights>
	<package-amount>250000</package-amount>
	<place>
		<domestic-place>
			<place-name>tea farms</place-name>
			<type>recreational</type>
			<travel-mode>bus</travel-mode>
			<hours>24</hours>
			<description>scenic beauty</description>
		</domestic-place>
		<domestic-place>
			<place-name>tiger hills</place-name>
			<type>adventure</type>
			<travel-mode>bus</travel-mode>
			<hours>12</hours>
			<description>animal adventures</description>
		</domestic-place>
	</place>
</tour-package>
