=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/policyjaxb/src/main/resources/policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.lic.org/insurance/policy"
	xmlns:lip="http://www.lic.org/insurance/policy"
	elementFormDefault="qualified">
	<xs:element name="policy" type="lip:policyType" />
	<xs:complexType name="policyType">
		<xs:sequence>
			<xs:element name="policyNo" type="xs:string" />
			<xs:element name="tenure" type="xs:int" />
			<xs:element name="insurredAmount" type="xs:int" />
			<xs:element name="memberInfo" type="lip:memberInfoType" />
			<xs:element name="plan" type="lip:planType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="memberInfoType">
		<xs:sequence>
			<xs:element name="fullName" type="xs:string" />
			<xs:element name="dob" type="xs:date" />
			<xs:element name="gender" type="xs:string" />
			<xs:element name="aadharNo" type="xs:string" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="planType">
		<xs:sequence>
			<xs:element name="planNo" type="xs:string" />
			<xs:element name="planName" type="xs:string" />
			<xs:element name="planType" type="xs:string" />
			<xs:element name="minEligibilityAge" type="xs:int" />
			<xs:element name="maxEligibilityAge" type="xs:int" />
			<xs:element name="minInsurredAmount" type="xs:float" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/policyjaxb/target/classes/policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<lip:policy xmlns:lip="http://www.lic.org/insurance/policy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.lic.org/insurance/policy policy.xsd ">
	<lip:policyNo>P0102012</lip:policyNo>
	<lip:tenure>12</lip:tenure>
	<lip:insurredAmount>120000</lip:insurredAmount>
	<lip:memberInfo>
		<lip:fullName>Himanshu Sharma</lip:fullName>
		<lip:dob>1998-07-01</lip:dob>
		<lip:gender>Male</lip:gender>
		<lip:aadharNo>2345 6743 5678</lip:aadharNo>
	</lip:memberInfo>
	<lip:plan>
		<lip:planNo>P00001</lip:planNo>
		<lip:planName>Surakhsa</lip:planName>
		<lip:planType>Risk Coverage</lip:planType>
		<lip:minEligibilityAge>18</lip:minEligibilityAge>
		<lip:maxEligibilityAge>65</lip:maxEligibilityAge>
		<lip:minInsurredAmount>100000</lip:minInsurredAmount>
	</lip:plan>
</lip:policy>
