=== himanshuhsshar/SOAP-and-Restful/XSD/account.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="account" type="accountType"/>
	<xs:complexType name="accountType">		
		<xs:all>
			<xs:element name="account-no" type="xs:string"/>
			<xs:element name="account-holder-name" type="xs:string"/>
			<xs:element name="account-type" type="xs:string"/>
			<xs:element name="mobile-no" type="xs:string"/>
			<xs:element name="email-address" type="xs:string"/>
			<xs:element name="branch-code" type="xs:string"/>
			<xs:element name="balance" type="xs:float"/>			
		</xs:all>
	</xs:complexType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/XSD/account.xml
<?xml version="1.0" encoding="UTF-8"?>
<account xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20223003/XSD/account.xsd">
	<account-no>ac939</account-no>
	<account-holder-name>bruke</account-holder-name>
	<account-type>savings</account-type>
	<mobile-no>939263859</mobile-no>
	<email-address>bruke@yahoo.com</email-address>
	<balance>9374</balance>
	<branch-code>b9384</branch-code>	
</account>

=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/account.xml
<?xml version="1.0" encoding="UTF-8"?>
<account xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebServices/XSD/account.xsd">
	<account-no>ac3678</account-no>
	<account-holder-name>Himanshu Sharma</account-holder-name>
	<account-type>Savings</account-type>
	<mobile-no>8109465904</mobile-no>
	<balance>56789</balance>
	<email-address>himanshu.hs951@gmail.com</email-address>
	<branch-code>9374</branch-code>
</account>
