=== himanshuhsshar/SOAP-and-Restful/XSD/classifieds.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
		
	<xs:element name="classifieds" type="classifiedsType"/>
	
	<xs:group name="propertyElementGroup">
		<xs:sequence>
			<xs:element name="type" type="xs:string"/>
			<xs:element name="facing" type="xs:string"/>
			<xs:element name="rental-amount" type="xs:float"/>
		</xs:sequence>
	</xs:group>	
	
	<xs:complexType name="classifiedsType">
		<xs:sequence>
			<xs:element name="flat" type="flatType" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="house" type="houseType" minOccurs="1" maxOccurs="unbounded"/>		
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="flatType">
		<xs:sequence>
			<xs:group ref="propertyElementGroup"/>
			<xs:element name="square-feet" type="xs:int"/>
			<xs:element name="floor" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="houseType">
		<xs:sequence>
			<xs:group ref="propertyElementGroup"/>
			<xs:element name="no-of-floors" type="xs:int"/>
			<xs:element name="square-yards" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/classifieds.xml
<?xml version="1.0" encoding="UTF-8"?>
<classifieds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebServices/XSD/classifieds.xsd">
	<flat>
		<type>2BHK</type>
		<facing>Ease</facing>
		<rental-amount>18000</rental-amount>
		<square-feet>1400</square-feet>
		<floor>2</floor>
	</flat>
	<house>
		<type>villa</type>
		<facing>North-East</facing>
		<rental-amount>75000</rental-amount>
		<no-of-floors>2</no-of-floors>
		<square-yards>40000</square-yards>
	</house>
</classifieds>

=== himanshuhsshar/SOAP-and-Restful/XSD/classifieds.xml
<?xml version="1.0" encoding="UTF-8"?>
<classifieds xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20223003/XSD/classifieds.xsd">
	<flat>
		<type>2bhk</type>
		<facing>east</facing>
		<rental-amount>18000</rental-amount>
		<square-feet>1400</square-feet>
		<floor>10</floor>
	</flat>
	<house>
		<type>villa</type>
		<facing>north-east</facing>
		<rental-amount>75000</rental-amount>
		<no-of-floors>2</no-of-floors>
		<square-yards>4000</square-yards>
	</house>
</classifieds>
