=== himanshuhsshar/SOAP-and-Restful/XSD/train-ticket.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="train-ticket" type="trainTicketType"/>
	<xs:complexType name="trainTicketType">
		<xs:sequence>
			<xs:element name="train-no" type="xs:string"/>
			<xs:element name="source" type="xs:string"/>
			<xs:element name="destination" type="xs:string"/>
			<xs:element name="journey-date" type="xs:date"/>
			<xs:element name="amount" type="xs:float"/>			
			<xs:element name="passengers" type="passengersType"/>
		</xs:sequence>	
		<xs:attribute name="coach-no" type="xs:string" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="passengersType">
		<xs:sequence>
			<xs:element name="passenger" type="passengerType" minOccurs="1" maxOccurs="6"/>		
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="passengerType">
		<xs:sequence>
			<xs:element name="fullname" type="xs:string"/>
			<xs:element name="age" type="xs:int"/>
			<xs:element name="gender" type="xs:string"/>		
		</xs:sequence>
		<xs:attribute name="berth-no" type="xs:int" use="required"/>
	</xs:complexType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/XSD/train-ticket.xml
<?xml version="1.0" encoding="UTF-8"?>
<train-ticket coach-no="s1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20223003/XSD/train-ticket.xsd">
	<train-no>t9303</train-no>
	<source>hyderabad</source>
	<destination>banglore</destination>
	<journey-date>2022-07-30</journey-date>
	<amount>1000</amount>
	<passengers>
		<passenger berth-no="32">
			<fullname>peter</fullname>
			<age>25</age>
			<gender>male</gender>
		</passenger>
	</passengers>
</train-ticket>

=== himanshuhsshar/SOAP-and-Restful/EXAMPLES/XSD/train-ticket.xml
<?xml version="1.0" encoding="UTF-8"?>
<train-ticket coach-no="s1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/WebServices/XSD/train-ticket.xsd">
	<train-no>t9309</train-no>
	<source>hyderabad</source>
	<destination>bangalore</destination>
	<journey-date>2022-07-30</journey-date>
	<amount>1000</amount>
	<passengers>
		<passenger berth-no="23">
			<fullname>peter</fullname>
			<age>25</age>
			<gender>Male</gender>
		</passenger>
	</passengers>
</train-ticket>
