=== himanshuhsshar/SOAP-and-Restful/MAY/policyjaxb/src/main/resources/policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.lic.org/insurance/policy"
	xmlns:lip="http://www.lic.org/insurance/policy"
	elementFormDefault="qualified">

	<xs:element name="policy" type="lip:policyType"/>
	
	<xs:complexType name="policyType">
		<xs:sequence>
			<xs:element name="policy-no" type="xs:string" />
			<xs:element name="tenure" type="xs:int" />
			<xs:element name="insurred-amount" type="xs:float" />
			<xs:element name="member-info" type="lip:memberInfoType" />
			<xs:element name="plan" type="lip:planType" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="memberInfoType">
		<xs:sequence>
			<xs:element name="fullname" type="xs:string" />
			<xs:element name="dob" type="xs:date" />
			<xs:element name="gender" type="xs:string" />
			<xs:element name="aadhar-no" type="xs:string" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="planType">
		<xs:sequence>
			<xs:element name="plan-no" type="xs:string" />
			<xs:element name="plan-name" type="xs:string" />
			<xs:element name="plan-type" type="xs:string" />
			<xs:element name="min-eligibility-age" type="xs:int" />
			<xs:element name="max-eligibility-age" type="xs:int" />
			<xs:element name="min-insurred-amount" type="xs:float" />
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== himanshuhsshar/SOAP-and-Restful/MAY/policyjaxb/src/main/resources/policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<lip:policy xmlns:lip="http://www.lic.org/insurance/policy"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.lic.org/insurance/policy policy.xsd ">
	<lip:policy-no>p03938093</lip:policy-no>
	<lip:tenure>60</lip:tenure>
	<lip:insurred-amount>120000</lip:insurred-amount>
	<!-- <lip:member-info>
		<lip:fullname>brandon k</lip:fullname>
		<lip:dob>2001-10-01</lip:dob>
		<lip:gender>Male</lip:gender>
		<lip:aadhar-no>ahd98383893</lip:aadhar-no>
	</lip:member-info> -->
	<lip:plan>
		<lip:plan-no>pl001</lip:plan-no>
		<lip:plan-name>Suraksha</lip:plan-name>
		<lip:plan-type>Risk Coverage</lip:plan-type>
		<lip:min-eligibility-age>18</lip:min-eligibility-age>
		<lip:max-eligibility-age>65</lip:max-eligibility-age>
		<lip:min-insurred-amount>100000</lip:min-insurred-amount>
	</lip:plan>
</lip:policy>
